repos:
  - repo: https://github.com/pycqa/pylint
    rev: v2.8.3
    hooks:
    - id: pylint
      args:
      - --disable=import-error,redefined-outer-name,unused-argument,too-few-public-methods,too-many-arguments
